[package]
name = "rnote"
version = "0.1.0"
authors = ["Volodymyr Patuta <6977238-fiplox@users.noreply.gitlab.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
